name: Android-apk-build

env:
  KEY: ${{ secrets.KEY }}
  CLUSTER: ${{ secrets.CLUSTER }}

on:
  workflow_dispatch:

jobs:
  build-android:
    name: 🤖 Android Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - name: Create .env file
        run: |
          echo "KEY=${KEY}" >> .env
          echo "CLUSTER=${CLUSTER}" >> .env

      - name: Build APK
        run: flutter build apk --release

      - name: Rename APK for upload
        run: mv build/app/outputs/flutter-apk/app-release.apk Mini_Service_Booking.apk

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Mini_Service_Booking.apk
          tag: v1.0
          overwrite: true
          body: "This is first Android release"
